package com.manajay.cay.bo;

import java.util.Date;

public class Photo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.id
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.url
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.title
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.description
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.gmt_create
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.gmt_modified
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.category
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    private Integer category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.id
     *
     * @return the value of photo.id
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.id
     *
     * @param id the value for photo.id
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.url
     *
     * @return the value of photo.url
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.url
     *
     * @param url the value for photo.url
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.title
     *
     * @return the value of photo.title
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.title
     *
     * @param title the value for photo.title
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.description
     *
     * @return the value of photo.description
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.description
     *
     * @param description the value for photo.description
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.gmt_create
     *
     * @return the value of photo.gmt_create
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.gmt_create
     *
     * @param gmtCreate the value for photo.gmt_create
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.gmt_modified
     *
     * @return the value of photo.gmt_modified
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.gmt_modified
     *
     * @param gmtModified the value for photo.gmt_modified
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.category
     *
     * @return the value of photo.category
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.category
     *
     * @param category the value for photo.category
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    @Override
    public String toString() {
        return "Photo{" +
                "id=" + id +
                ", url='" + url + '\'' +
                ", title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", gmtCreate=" + gmtCreate +
                ", gmtModified=" + gmtModified +
                ", category=" + category +
                '}';
    }
}