package com.lj.spring.mapper;

import com.lj.spring.bean.Orders;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Aug 07 15:38:36 CST 2017
     */
    @Delete({
        "delete from orders",
        "where order_id = #{orderId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Aug 07 15:38:36 CST 2017
     */
    @Insert({
        "insert into orders (order_id, order_no, ",
        "order_price)",
        "values (#{orderId,jdbcType=INTEGER}, #{orderNo,jdbcType=VARCHAR}, ",
        "#{orderPrice,jdbcType=REAL})"
    })
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Aug 07 15:38:36 CST 2017
     */
    @Select({
        "select",
        "order_id, order_no, order_price",
        "from orders",
        "where order_id = #{orderId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="order_no", property="orderNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="order_price", property="orderPrice", jdbcType=JdbcType.REAL)
    })
    Orders selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Aug 07 15:38:36 CST 2017
     */
    @Select({
        "select",
        "order_id, order_no, order_price",
        "from orders",
        "order by order_id desc,order_no asc"
    })
    @Results({
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="order_no", property="orderNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="order_price", property="orderPrice", jdbcType=JdbcType.REAL)
    })
    List<Orders> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Aug 07 15:38:36 CST 2017
     */
    @Update({
        "update orders",
        "set order_no = #{orderNo,jdbcType=VARCHAR},",
          "order_price = #{orderPrice,jdbcType=REAL}",
        "where order_id = #{orderId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Orders record);
}