server:
  port: 8080
  context-path: /cay

spring:
  datasource:
    names: mybatis,mysql
    mybatis:
      url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    mysql:
      url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver


mywebsite: http://manajay.com


rsa:
  key: rsakey
  value: rsa
