package com.manajay.cay.mapper.mysql;

import com.manajay.cay.bo.Photo;

import java.util.List;

public interface MysqlPhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    int insert(Photo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    Photo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    List<Photo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo
     *
     * @mbg.generated Sat Dec 16 21:30:52 CST 2017
     */
    int updateByPrimaryKey(Photo record);
}